// DISCLAIMER:
// This file has been generated by AI

import { DestroyRef, Directive, ElementRef, NgZone, afterNextRender, inject } from "@angular/core";

@Directive({
  selector: "[fitText]",
})
export class FitTextDirective {
  private element = inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  private destroyRef = inject(DestroyRef);
  private zone = inject(NgZone);

  private resizeObserver?: ResizeObserver;
  private mutationObserver?: MutationObserver;
  private frame = 0;

  constructor() {
    afterNextRender({
      write: () => {
        const parent = this.element.parentElement;

        if (!parent || typeof ResizeObserver === "undefined") return;

        this.element.style.whiteSpace = "nowrap";
        this.element.style.maxWidth = "none";

        const fit = () => {
          cancelAnimationFrame(this.frame);

          this.frame = requestAnimationFrame(() => {
            const parentWidth = parent.clientWidth;

            if (parentWidth <= 0) return;

            this.element.style.fontSize = "";

            const max = Number.parseFloat(getComputedStyle(this.element).fontSize) || 32;
            let low = 4;
            let high = max;

            this.element.style.fontSize = `${max}px`;

            if (this.element.scrollWidth <= parentWidth) return;

            for (let i = 0; i < 8; i++) {
              const mid = (low + high) / 2;
              this.element.style.fontSize = `${mid}px`;

              if (this.element.scrollWidth > parentWidth) {
                high = mid;
              } else {
                low = mid;
              }
            }

            this.element.style.fontSize = `${low}px`;
          });
        };

        this.zone.runOutsideAngular(() => {
          this.resizeObserver = new ResizeObserver(fit);
          this.resizeObserver.observe(parent);
          this.resizeObserver.observe(this.element);

          this.mutationObserver = new MutationObserver(fit);
          this.mutationObserver.observe(this.element, {
            childList: true,
            characterData: true,
            subtree: true,
          });

          document.fonts?.ready.then(fit);
          fit();
        });

        this.destroyRef.onDestroy(() => {
          this.resizeObserver?.disconnect();
          this.mutationObserver?.disconnect();
          cancelAnimationFrame(this.frame);
        });
      },
    });
  }
}
