// DISCLAIMER:
// This file was completely generated by AI.
// I tried to find existing implementations but none were specific to Angular (integration with signals).

import { isPlatformBrowser } from "@angular/common";
import { PLATFORM_ID, Signal, computed, effect, inject, signal } from "@angular/core";
import { createStore, get, set } from "idb-keyval";

let defaultStore: ReturnType<typeof createStore> | undefined;

function getDefaultStore() {
  return (defaultStore ??=
    typeof indexedDB !== "undefined" ? createStore("app-storage", "keyval") : undefined);
}

// Shallow clones root objects so users can mutate safely in .update()
function clone<T>(value: T): T {
  if (value instanceof Set) return new Set(value) as T;
  if (value instanceof Map) return new Map(value) as T;
  if (Array.isArray(value)) return [...value] as T;
  if (value !== null && typeof value === "object") return { ...value } as T;
  return value;
}

type ReadonlyStoredValue<T> =
  T extends Set<infer V>
    ? ReadonlySet<V>
    : T extends Map<infer K, infer V>
      ? ReadonlyMap<K, V>
      : T extends Array<infer V>
        ? readonly V[]
        : Readonly<T>;

export type StorageSignal<T> = Signal<ReadonlyStoredValue<T>> & {
  readonly loaded: Signal<boolean>;
  readonly ready: Promise<void>;
  set(value: T): void;
  /** Supports both returning a new value, OR mutating the cloned draft and returning nothing */
  update(updater: (draft: T) => T | void): void;
};

function storageBase<T>(
  key: IDBValidKey,
  initialValue: T,
  options: {
    store?: ReturnType<typeof createStore>;
    debounceMs?: number;
    onError?: (error: unknown) => void;
  } = {},
): StorageSignal<T> {
  const isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
  const store = options.store ?? (isBrowser ? getDefaultStore() : undefined);
  const raw = signal<T>(initialValue);
  const loaded = signal(false);

  let dirtyBeforeLoad = false;

  const commit = (next: T) => {
    if (!loaded()) dirtyBeforeLoad = true;
    raw.set(next);
  };

  const ready = isBrowser
    ? get<T>(key, store)
        .then((stored) => {
          if (!dirtyBeforeLoad && stored !== undefined) raw.set(stored);
        })
        .catch(options.onError)
        .finally(() => loaded.set(true))
    : Promise.resolve().then(() => loaded.set(true));

  effect((onCleanup) => {
    if (!loaded() || !isBrowser) return;
    const current = raw();
    const timeoutId = setTimeout(
      () => void set(key, current, store).catch(options.onError),
      options.debounceMs ?? 0,
    );
    onCleanup(() => clearTimeout(timeoutId));
  });

  return Object.assign(
    computed(() => raw() as ReadonlyStoredValue<T>),
    {
      loaded: loaded.asReadonly(),
      ready,
      set: commit,
      update: (fn: (draft: T) => T | void) => {
        const draft = clone(raw());
        const result = fn(draft);
        // If the user returns nothing (undefined), commit the draft they mutated
        commit(result !== undefined ? result : draft);
      },
    },
  );
}

export const storage = Object.assign(storageBase, {
  /**
   * Asynchronously fetches a value directly from IndexedDB.
   * Does NOT create a Signal or require an Injection Context.
   */
  async get<T, C extends boolean = false>(
    key: IDBValidKey,
    initialValue: T,
    options: {
      store?: ReturnType<typeof createStore>;
      onError?: (error: unknown) => void;
      clone?: C;
    } = {},
  ): Promise<C extends true ? T : ReadonlyStoredValue<T>> {
    let storedValue: T | undefined;

    if (typeof indexedDB !== "undefined") {
      try {
        storedValue = await get<T>(key, options.store ?? getDefaultStore());
      } catch (error) {
        options.onError?.(error);
      }
    }

    const finalValue = storedValue !== undefined ? storedValue : initialValue;

    return (options.clone ? clone(finalValue) : finalValue) as any;
  },
});
