// DISCLAIMER:
// This file was completely generated by AI.
// I tried to find existing implementations but none were specific to Angular (integration with signals).

import { isPlatformBrowser } from '@angular/common';
import {
  DestroyRef,
  PLATFORM_ID,
  Signal,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { createStore, get, set } from 'idb-keyval';

let defaultStore: ReturnType<typeof createStore> | undefined;

function getDefaultStore() {
  if (!defaultStore && typeof indexedDB !== 'undefined') {
    defaultStore = createStore('app-storage', 'keyval');
  }
  return defaultStore;
}

type IdbStore = ReturnType<typeof createStore>;

type ReadonlyStoredValue<T> =
  T extends Set<infer V> ? ReadonlySet<V> :
  T extends Map<infer K, infer V> ? ReadonlyMap<K, V> :
  T extends Array<infer V> ? readonly V[] :
  Readonly<T>;

type BaseStorageSignal<T> = Signal<ReadonlyStoredValue<T>> & {
  readonly loaded: Signal<boolean>;
  readonly ready: Promise<void>;
  replace(value: T): void;
  set(value: T): void;
  update(updater: (current: T) => T): void;
};

type SetOps<T> = {
  add(value: T): void;
  delete(value: T): boolean;
  clear(): void;
};

type MapOps<K, V> = {
  set(key: K, value: V): void;
  delete(key: K): boolean;
  clear(): void;
};

type ArrayOps<T> = {
  push(...values: T[]): number;
  remove(predicate: (value: T, index: number, array: readonly T[]) => boolean): number;
  splice(start: number, deleteCount?: number, ...items: T[]): readonly T[];
  clear(): void;
};

export type StorageSignal<T> =
  BaseStorageSignal<T> &
  (
    T extends Set<infer V> ? SetOps<V> :
    T extends Map<infer K, infer V> ? MapOps<K, V> :
    T extends Array<infer V> ? ArrayOps<V> :
    unknown
  );

export function storage<T>(
  key: IDBValidKey,
  initialValue: T,
  options: {
    store?: IdbStore;
    debounceMs?: number;
    onError?: (error: unknown) => void;
  } = {},
): StorageSignal<T> {
  const destroyRef = inject(DestroyRef);
  const platformId = inject(PLATFORM_ID);
  const isBrowser = isPlatformBrowser(platformId);

  const store = options.store ?? (isBrowser ? getDefaultStore() : undefined);
  const debounceMs = options.debounceMs ?? 0;

  const raw = signal<T>(cloneMutableValue(initialValue));
  const loaded = signal(false);

  let dirtyBeforeLoad = false;

  const commit = (next: T): void => {
    if (!loaded()) {
      dirtyBeforeLoad = true;
    }

    raw.set(next);
  };

  const ready = isBrowser
    ? get<T>(key, store)
        .then((stored) => {
          if (!dirtyBeforeLoad && stored !== undefined) {
            raw.set(cloneMutableValue(stored));
          }
        })
        .catch((error) => {
          options.onError?.(error);
        })
        .finally(() => {
          loaded.set(true);
        })
    : Promise.resolve().then(() => {
        loaded.set(true);
      });

  const persistEffect = effect((onCleanup) => {
    if (!loaded() || !isBrowser) {
      return;
    }

    const current = raw();

    const timeoutId = setTimeout(() => {
      void set(key, current, store).catch((error) => {
        options.onError?.(error);
      });
    }, debounceMs);

    onCleanup(() => {
      clearTimeout(timeoutId);
    });
  });

  destroyRef.onDestroy(() => {
    persistEffect.destroy();
  });

  const readonlyValue = computed(() => {
    return toReadonlyValue(raw()) as ReadonlyStoredValue<T>;
  });

  const base = Object.assign(readonlyValue, {
    loaded: loaded.asReadonly(),
    ready,

    replace(value: T): void {
      commit(cloneMutableValue(value));
    },

    set(value: T): void {
      commit(cloneMutableValue(value));
    },

    update(updater: (current: T) => T): void {
      commit(cloneMutableValue(updater(raw())));
    },
  });

  if (initialValue instanceof Set) {
    return Object.assign(base, {
      add(value: unknown): void {
        const next = new Set(raw() as Set<unknown>);
        next.add(value);
        commit(next as T);
      },

      delete(value: unknown): boolean {
        const current = raw() as Set<unknown>;
        if (!current.has(value)) {
          return false;
        }
        const next = new Set(current);
        const deleted = next.delete(value);
        commit(next as T);
        return deleted;
      },

      clear(): void {
        const current = raw() as Set<unknown>;
        if (current.size === 0) {
          return;
        }
        commit(new Set() as T);
      },
    }) as unknown as StorageSignal<T>;
  }

  if (initialValue instanceof Map) {
    return Object.assign(base, {
      set(keyOrValue: unknown, value?: unknown): void {
        if (arguments.length === 1) {
          commit(cloneMutableValue(keyOrValue as T));
        } else {
          const next = new Map(raw() as Map<unknown, unknown>);
          next.set(keyOrValue, value);
          commit(next as T);
        }
      },

      delete(key: unknown): boolean {
        const current = raw() as Map<unknown, unknown>;

        if (!current.has(key)) {
          return false;
        }

        const next = new Map(current);
        const deleted = next.delete(key);

        commit(next as T);

        return deleted;
      },

      clear(): void {
        const current = raw() as Map<unknown, unknown>;

        if (current.size === 0) {
          return;
        }

        commit(new Map() as T);
      },
    }) as unknown as StorageSignal<T>;
  }

  if (Array.isArray(initialValue)) {
    return Object.assign(base, {
      push(...values: unknown[]): number {
        const next = [...(raw() as unknown[]), ...values];
        commit(next as T);
        return next.length;
      },

      remove(
        predicate: (
          value: unknown,
          index: number,
          array: readonly unknown[],
        ) => boolean,
      ): number {
        const current = raw() as unknown[];

        let removed = 0;

        const next = current.filter((value, index) => {
          const shouldRemove = predicate(value, index, current);

          if (shouldRemove) {
            removed++;
          }

          return !shouldRemove;
        });

        if (removed > 0) {
          commit(next as T);
        }

        return removed;
      },

      splice(start: number, deleteCount = Number.MAX_SAFE_INTEGER, ...items: unknown[]): readonly unknown[] {
        const next = [...(raw() as unknown[])];
        const removed = next.splice(start, deleteCount, ...items);

        commit(next as T);

        return Object.freeze([...removed]);
      },

      clear(): void {
        const current = raw() as unknown[];

        if (current.length === 0) {
          return;
        }

        commit([] as T);
      },
    }) as unknown as StorageSignal<T>;
  }

  return base as unknown as StorageSignal<T>;
}

function cloneMutableValue<T>(value: T): T {
  if (value instanceof Set) {
    return new Set(value) as T;
  }

  if (value instanceof Map) {
    return new Map(value) as T;
  }

  if (Array.isArray(value)) {
    return [...value] as T;
  }

  return value;
}

function toReadonlyValue<T>(value: T): unknown {
  if (value instanceof Set) {
    return new Proxy(value, {
      get(target, prop) {
        if (prop === 'add' || prop === 'delete' || prop === 'clear') {
          return undefined;
        }
        const val = (target as any)[prop];
        if (typeof val === 'function') {
          return val.bind(target);
        }
        return val;
      }
    });
  }

  if (value instanceof Map) {
    return new Proxy(value, {
      get(target, prop) {
        if (prop === 'set' || prop === 'delete' || prop === 'clear') {
          return undefined;
        }
        const val = (target as any)[prop];
        if (typeof val === 'function') {
          return val.bind(target);
        }
        return val;
      }
    });
  }

  if (Array.isArray(value)) {
    return Object.freeze([...value]);
  }

  return value;
}