// DISCLAIMER:
// This file has been generated with AI.
// There's no way I'm mapping everything by hand.
// I did my best to format it to be legible, though (manually, because AI is stupid and can't see).

import { type } from "arktype";

/* @formatter:off */

export const hiraganaDakuten = {
  ga: ["が", "ぎ", "ぐ", "げ", "ご"],
  za: ["ざ", "じ", "ず", "ぜ", "ぞ"],
  da: ["だ", null, "づ", "で", "ど"],
  ba: ["ば", "び", "ぶ", "べ", "ぼ"],
} as const;
export const hiraganaDakutenChars = [
  ...hiraganaDakuten.ga,
  ...hiraganaDakuten.za,
  ...hiraganaDakuten.da,
  ...hiraganaDakuten.ba,
] as const;
export const hiraganaHandakuten = {
  pa: ["ぱ", "ぴ", "ぷ", "ぺ", "ぽ"],
} as const;
export const hiraganaHandakutenChars = hiraganaHandakuten.pa;
export const hiraganaYouon = {
  kya: ["きゃ", null, "きゅ", null, "きょ"],
  sha: ["しゃ", null, "しゅ", null, "しょ"],
  cha: ["ちゃ", null, "ちゅ", null, "ちょ"],
  nya: ["にゃ", null, "にゅ", null, "にょ"],
  hya: ["ひゃ", null, "ひゅ", null, "ひょ"],
  mya: ["みゃ", null, "みゅ", null, "みょ"],
  rya: ["りゃ", null, "りゅ", null, "りょ"],
  gya: ["ぎゃ", null, "ぎゅ", null, "ぎょ"],
  ja: ["じゃ", null, "じゅ", null, "じょ"],
  bya: ["びゃ", null, "びゅ", null, "びょ"],
  pya: ["ぴゃ", null, "ぴゅ", null, "ぴょ"],
} as const;
export const hiraganaYouonChars = [
  ...hiraganaYouon.kya,
  ...hiraganaYouon.sha,
  ...hiraganaYouon.cha,
  ...hiraganaYouon.nya,
  ...hiraganaYouon.hya,
  ...hiraganaYouon.mya,
  ...hiraganaYouon.rya,
  ...hiraganaYouon.gya,
  ...hiraganaYouon.ja,
  ...hiraganaYouon.bya,
  ...hiraganaYouon.pya,
] as const;
export const hiraganaSmall = {
  sokuon: ["っ", null, null, null, null],
  smallYa: ["ゃ", null, "ゅ", null, "ょ"],
} as const;
export const hiraganaSmallChars = [...hiraganaSmall.sokuon, ...hiraganaSmall.smallYa] as const;
export const hiragana = {
  a: ["あ", "い", "う", "え", "お"],
  ka: ["か", "き", "く", "け", "こ"],
  sa: ["さ", "し", "す", "せ", "そ"],
  ta: ["た", "ち", "つ", "て", "と"],
  na: ["な", "に", "ぬ", "ね", "の"],
  ha: ["は", "ひ", "ふ", "へ", "ほ"],
  ma: ["ま", "み", "む", "め", "も"],
  ya: ["や", null, "ゆ", null, "よ"],
  ra: ["ら", "り", "る", "れ", "ろ"],
  wa: ["わ", null, null, null, "を"],
  n: ["ん", null, null, null, null],
  ...hiraganaDakuten,
  ...hiraganaHandakuten,
  ...hiraganaYouon,
  ...hiraganaSmall,
} as const;
export const hiraganaChoon = {
  u_: "うー",
  e_: "えー",
  fu_: "ふー",
  he_: "へー",
} as const;
export const hiraganaSokuon = {
  kka: "っか",
  kki: "っき",
  kku: "っく",
  kke: "っけ",
  kko: "っこ",
  ssa: "っさ",
  sshi: "っし",
  ssu: "っす",
  sse: "っせ",
  sso: "っそ",
  tta: "った",
  cchi: "っち",
  ttsu: "っつ",
  tte: "って",
  tto: "っと",
  ppa: "っぱ",
  ppi: "っぴ",
  ppu: "っぷ",
  ppe: "っぺ",
  ppo: "っぽ",
  kkya: "っきゃ",
  kkyu: "っきゅ",
  kkyo: "っきょ",
  ssha: "っしゃ",
  sshu: "っしゅ",
  ssho: "っしょ",
  ccha: "っちゃ",
  cchu: "っちゅ",
  ccho: "っちょ",
  ppya: "っぴゃ",
  ppyu: "っぴゅ",
  ppyo: "っぴょ",
} as const;

export const katakanaDakuten = {
  ga: ["ガ", "ギ", "グ", "ゲ", "ゴ"],
  za: ["ザ", "ジ", "ズ", "ゼ", "ゾ"],
  da: ["ダ", null, null, "デ", "ド"],
  ba: ["バ", "ビ", "ブ", "ベ", "ボ"],
} as const;
export const katakanaDakutenChars = [
  ...katakanaDakuten.ga,
  ...katakanaDakuten.za,
  ...katakanaDakuten.da,
  ...katakanaDakuten.ba,
] as const;
export const katakanaHandakuten = {
  pa: ["パ", "ピ", "プ", "ペ", "ポ"],
} as const;
export const katakanaHandakutenChars = katakanaHandakuten.pa;
export const katakanaYouon = {
  kya: ["キャ", null, "キュ", null, "キョ"],
  sha: ["シャ", null, "シュ", null, "ショ"],
  cha: ["チャ", null, "チュ", null, "チョ"],
  nya: ["ニャ", null, "ニュ", null, "ニョ"],
  hya: ["ヒャ", null, "ヒュ", null, "ヒョ"],
  mya: ["ミャ", null, "ミュ", null, "ミョ"],
  rya: ["リャ", null, "リュ", null, "リョ"],
  gya: ["ギャ", null, "ギュ", null, "ギョ"],
  ja: ["ジャ", null, "ジュ", null, "ジョ"],
  bya: ["ビャ", null, "ビュ", null, "ビョ"],
  pya: ["ピャ", null, "ピュ", null, "ピョ"],
} as const;
export const katakanaYouonChars = [
  ...katakanaYouon.kya,
  ...katakanaYouon.sha,
  ...katakanaYouon.cha,
  ...katakanaYouon.nya,
  ...katakanaYouon.hya,
  ...katakanaYouon.mya,
  ...katakanaYouon.rya,
  ...katakanaYouon.gya,
  ...katakanaYouon.ja,
  ...katakanaYouon.bya,
  ...katakanaYouon.pya,
] as const;
export const katakanaExtended = {
  wi: ["ウィ", null, null, "ウェ", "ウォ"],
  va: ["ヴァ", "ヴィ", "ヴ", "ヴェ", "ヴォ"],
  she: ["シェ", null, null, null, null],
  je: ["ジェ", null, null, null, null],
  che: ["チェ", null, null, null, null],
  tsa: ["ツァ", "ツィ", null, "ツェ", "ツォ"],
  ti: ["ティ", null, null, null, null],
  tu: ["トゥ", null, null, null, null],
  di: ["ディ", null, null, null, null],
  du: ["ドゥ", null, null, null, null],
  fa: ["ファ", "フィ", null, "フェ", "フォ"],
  fya: ["フャ", null, "フュ", null, "フョ"],
} as const;
export const katakanaExtendedChars = [
  ...katakanaExtended.wi,
  ...katakanaExtended.va,
  ...katakanaExtended.she,
  ...katakanaExtended.je,
  ...katakanaExtended.che,
  ...katakanaExtended.tsa,
  ...katakanaExtended.ti,
  ...katakanaExtended.tu,
  ...katakanaExtended.di,
  ...katakanaExtended.du,
  ...katakanaExtended.fa,
  ...katakanaExtended.fya,
] as const;
export const katakanaSmall = {
  sokuon: ["ッ", null, null, null, null],
  smallA: ["ァ", null, null, null, null],
} as const;
export const katakanaSmallChars = [...katakanaSmall.sokuon, ...katakanaSmall.smallA] as const;
export const katakana = {
  a: ["ア", "イ", "ウ", "エ", "オ"],
  ka: ["カ", "キ", "ク", "ケ", "コ"],
  sa: ["サ", "シ", "ス", "セ", "ソ"],
  ta: ["タ", "チ", "ツ", "テ", "ト"],
  na: ["ナ", "ニ", "ヌ", "ネ", "ノ"],
  ha: ["ハ", "ヒ", "フ", "ヘ", "ホ"],
  ma: ["マ", "ミ", "ム", "メ", "モ"],
  ya: ["ヤ", null, "ユ", null, "ヨ"],
  ra: ["ラ", "リ", "ル", "レ", "ロ"],
  wa: ["ワ", null, null, null, "ヲ"],
  n: ["ン", null, null, null, null],
  ...katakanaDakuten,
  ...katakanaHandakuten,
  ...katakanaYouon,
  ...katakanaExtended,
  ...katakanaSmall,
} as const;
export const katakanaChoon = {
  a_: "アー",
  i_: "イー",
  u_: "ウー",
  e_: "エー",
  o_: "オー",
  ka_: "カー",
  ki_: "キー",
  ku_: "クー",
  ke_: "ケー",
  ko_: "コー",
  sa_: "サー",
  shi_: "シー",
  su_: "スー",
  se_: "セー",
  so_: "ソー",
  ta_: "ター",
  chi_: "チー",
  tsu_: "ツー",
  te_: "テー",
  to_: "トー",
  na_: "ナー",
  ni_: "ニー",
  nu_: "ヌー",
  ne_: "ネー",
  no_: "ノー",
  ha_: "ハー",
  hi_: "ヒー",
  fu_: "フー",
  he_: "ヘー",
  ho_: "ホー",
  ma_: "マー",
  mi_: "ミー",
  mu_: "ムー",
  me_: "メー",
  mo_: "モー",
  ya_: "ヤー",
  yu_: "ユー",
  yo_: "ヨー",
  ra_: "ラー",
  ri_: "リー",
  ru_: "ルー",
  re_: "レー",
  ro_: "ロー",
  wa_: "ワー",
  wo_: "ヲー",
  n_: "ンー",
  ga_: "ガー",
  gi_: "ギー",
  gu_: "グー",
  ge_: "ゲー",
  go_: "ゴー",
  za_: "ザー",
  ji_: "ジー",
  zu_: "ズー",
  ze_: "ゼー",
  zo_: "ゾー",
  da_: "ダー",
  de_: "デー",
  do_: "ドー",
  ba_: "バー",
  bi_: "ビー",
  bu_: "ブー",
  be_: "ベー",
  bo_: "ボー",
  pa_: "パー",
  pi_: "ピー",
  pu_: "プー",
  pe_: "ペー",
  po_: "ポー",
  kya_: "キャー",
  kyu_: "キュー",
  kyo_: "キョー",
  sha_: "シャー",
  shu_: "シュー",
  sho_: "ショー",
  cha_: "チャー",
  chu_: "チュー",
  cho_: "チョー",
  nya_: "ニャー",
  nyu_: "ニュー",
  nyo_: "ニョー",
  hya_: "ヒャー",
  hyu_: "ヒュー",
  hyo_: "ヒョー",
  mya_: "ミャー",
  myu_: "ミュー",
  myo_: "ミョー",
  rya_: "リャー",
  ryu_: "リュー",
  ryo_: "リョー",
  gya_: "ギャー",
  gyu_: "ギュー",
  gyo_: "ギョー",
  ja_: "ジャー",
  ju_: "ジュー",
  jo_: "ジョー",
  bya_: "ビャー",
  byu_: "ビュー",
  byo_: "ビョー",
  pya_: "ピャー",
  pyu_: "ピュー",
  pyo_: "ピョー",
  wi_: "ウィー",
  we_: "ウェー",
  woAlt_: "ウォー",
  va_: "ヴァー",
  vi_: "ヴィー",
  vu_: "ヴー",
  ve_: "ヴェー",
  vo_: "ヴォー",
  she_: "シェー",
  je_: "ジェー",
  che_: "チェー",
  tsa_: "ツァー",
  tsi_: "ツィー",
  tse_: "ツェー",
  tso_: "ツォー",
  ti_: "ティー",
  tu_: "トゥー",
  di_: "ディー",
  du_: "ドゥー",
  fa_: "ファー",
  fi_: "フィー",
  fe_: "フェー",
  fo_: "フォー",
  fya_: "フャー",
  fyu_: "フュー",
  fyo_: "フョー",
} as const;
export const katakanaSokuon = {
  kka: "ッカ",
  kki: "ッキ",
  kku: "ック",
  kke: "ッケ",
  kko: "ッコ",
  ssa: "ッサ",
  sshi: "ッシ",
  ssu: "ッス",
  sse: "ッセ",
  sso: "ッソ",
  tta: "ッタ",
  cchi: "ッチ",
  ttsu: "ッツ",
  tte: "ッテ",
  tto: "ット",
  gga: "ッガ",
  ggi: "ッギ",
  ggu: "ッグ",
  gge: "ッゲ",
  ggo: "ッゴ",
  dda: "ッダ",
  dde: "ッデ",
  ddo: "ッド",
  ppa: "ッパ",
  ppi: "ッピ",
  ppu: "ップ",
  ppe: "ッペ",
  ppo: "ッポ",
  ffu: "ッフ",
  tti: "ッティ",
  kkaa: "ッカー",
  kkii: "ッキー",
  ssaa: "ッサー",
  ssee: "ッセー",
  ttaa: "ッター",
  kkya: "ッキャ",
  kkyu: "ッキュ",
  kkyo: "ッキョ",
  ssha: "ッシャ",
  sshu: "ッシュ",
  ssho: "ッショ",
  ccha: "ッチャ",
  cchu: "ッチュ",
  ccho: "ッチョ",
  ppya: "ッピャ",
  ppyu: "ッピュ",
  ppyo: "ッピョ",
  ppaa: "っパー",
} as const;

// prettier-ignore
export const toHiragana = {
    a: hiragana.a  [0],   i: hiragana.a [1],   u: hiragana.a  [2],  e: hiragana.a [3],   o: hiragana.a  [4],
   ka: hiragana.ka [0],  ki: hiragana.ka[1],  ku: hiragana.ka [2], ke: hiragana.ka[3],  ko: hiragana.ka [4],
   sa: hiragana.sa [0], shi: hiragana.sa[1],  su: hiragana.sa [2], se: hiragana.sa[3],  so: hiragana.sa [4],
   ta: hiragana.ta [0], chi: hiragana.ta[1], tsu: hiragana.ta [2], te: hiragana.ta[3],  to: hiragana.ta [4],
   na: hiragana.na [0],  ni: hiragana.na[1],  nu: hiragana.na [2], ne: hiragana.na[3],  no: hiragana.na [4],
   ha: hiragana.ha [0],  hi: hiragana.ha[1],  fu: hiragana.ha [2], he: hiragana.ha[3],  ho: hiragana.ha [4],
   ma: hiragana.ma [0],  mi: hiragana.ma[1],  mu: hiragana.ma [2], me: hiragana.ma[3],  mo: hiragana.ma [4],
   ya: hiragana.ya [0],                       yu: hiragana.ya [2],                      yo: hiragana.ya [4],
   ra: hiragana.ra [0],  ri: hiragana.ra[1],  ru: hiragana.ra [2], re: hiragana.ra[3],  ro: hiragana.ra [4],
   wa: hiragana.wa [0],                                                                 wo: hiragana.wa [4],
    n: hiragana.n  [0],
   ga: hiragana.ga [0],  gi: hiragana.ga[1],  gu: hiragana.ga [2], ge: hiragana.ga[3],  go: hiragana.ga [4],
   za: hiragana.za [0],  ji: hiragana.za[1],  zu: hiragana.za [2], ze: hiragana.za[3],  zo: hiragana.za [4],
   da: hiragana.da [0],                      zuAlt: hiragana.da[2], de: hiragana.da[3],  do: hiragana.da [4],
   ba: hiragana.ba [0],  bi: hiragana.ba[1],  bu: hiragana.ba [2], be: hiragana.ba[3],  bo: hiragana.ba [4],
   pa: hiragana.pa [0],  pi: hiragana.pa[1],  pu: hiragana.pa [2], pe: hiragana.pa[3],  po: hiragana.pa [4],
  kya: hiragana.kya[0],                      kyu: hiragana.kya[2],                     kyo: hiragana.kya[4],
  sha: hiragana.sha[0],                      shu: hiragana.sha[2],                     sho: hiragana.sha[4],
  cha: hiragana.cha[0],                      chu: hiragana.cha[2],                     cho: hiragana.cha[4],
  nya: hiragana.nya[0],                      nyu: hiragana.nya[2],                     nyo: hiragana.nya[4],
  hya: hiragana.hya[0],                      hyu: hiragana.hya[2],                     hyo: hiragana.hya[4],
  mya: hiragana.mya[0],                      myu: hiragana.mya[2],                     myo: hiragana.mya[4],
  rya: hiragana.rya[0],                      ryu: hiragana.rya[2],                     ryo: hiragana.rya[4],
  gya: hiragana.gya[0],                      gyu: hiragana.gya[2],                     gyo: hiragana.gya[4],
   ja: hiragana.ja [0],                       ju: hiragana.ja [2],                      jo: hiragana.ja [4],
  bya: hiragana.bya[0],                      byu: hiragana.bya[2],                     byo: hiragana.bya[4],
  pya: hiragana.pya[0],                      pyu: hiragana.pya[2],                     pyo: hiragana.pya[4],
 sokuon: hiragana.sokuon[0],
 yaSmall: hiragana.smallYa[0],       yuSmall: hiragana.smallYa[2],           yoSmall: hiragana.smallYa[4],
  ...hiraganaChoon,
  ...hiraganaSokuon
} as const;

// prettier-ignore
export const fromHiragana = {
  [hiragana.a  [0]]:   'a', [hiragana.a [1]]:   'i', [hiragana.a  [2]]:   'u', [hiragana.a [3]]:  'e', [hiragana.a  [4]]:   'o',
  [hiragana.ka [0]]:  'ka', [hiragana.ka[1]]:  'ki', [hiragana.ka [2]]:  'ku', [hiragana.ka[3]]: 'ke', [hiragana.ka [4]]:  'ko',
  [hiragana.sa [0]]:  'sa', [hiragana.sa[1]]: 'shi', [hiragana.sa [2]]:  'su', [hiragana.sa[3]]: 'se', [hiragana.sa [4]]:  'so',
  [hiragana.ta [0]]:  'ta', [hiragana.ta[1]]: 'chi', [hiragana.ta [2]]: 'tsu', [hiragana.ta[3]]: 'te', [hiragana.ta [4]]:  'to',
  [hiragana.na [0]]:  'na', [hiragana.na[1]]:  'ni', [hiragana.na [2]]:  'nu', [hiragana.na[3]]: 'ne', [hiragana.na [4]]:  'no',
  [hiragana.ha [0]]:  'ha', [hiragana.ha[1]]:  'hi', [hiragana.ha [2]]:  'fu', [hiragana.ha[3]]: 'he', [hiragana.ha [4]]:  'ho',
  [hiragana.ma [0]]:  'ma', [hiragana.ma[1]]:  'mi', [hiragana.ma [2]]:  'mu', [hiragana.ma[3]]: 'me', [hiragana.ma [4]]:  'mo',
  [hiragana.ya [0]]:  'ya',                          [hiragana.ya [2]]:  'yu',                         [hiragana.ya [4]]:  'yo',
  [hiragana.ra [0]]:  'ra', [hiragana.ra[1]]:  'ri', [hiragana.ra [2]]:  'ru', [hiragana.ra[3]]: 're', [hiragana.ra [4]]:  'ro',
  [hiragana.wa [0]]:  'wa',                                                                            [hiragana.wa [4]]:  'wo',
  [hiragana.n  [0]]:   'n',
  [hiragana.ga [0]]:  'ga', [hiragana.ga[1]]:  'gi', [hiragana.ga [2]]:  'gu', [hiragana.ga[3]]: 'ge', [hiragana.ga [4]]:  'go',
  [hiragana.za [0]]:  'za', [hiragana.za[1]]:  'ji', [hiragana.za [2]]:  'zu', [hiragana.za[3]]: 'ze', [hiragana.za [4]]:  'zo',
  [hiragana.da [0]]:  'da',                          [hiragana.da [2]]:  'zu', [hiragana.da[3]]: 'de', [hiragana.da [4]]:  'do',
  [hiragana.ba [0]]:  'ba', [hiragana.ba[1]]:  'bi', [hiragana.ba [2]]:  'bu', [hiragana.ba[3]]: 'be', [hiragana.ba [4]]:  'bo',
  [hiragana.pa [0]]:  'pa', [hiragana.pa[1]]:  'pi', [hiragana.pa [2]]:  'pu', [hiragana.pa[3]]: 'pe', [hiragana.pa [4]]:  'po',
  [hiragana.kya[0]]: 'kya',                          [hiragana.kya[2]]: 'kyu',                         [hiragana.kya[4]]: 'kyo',
  [hiragana.sha[0]]: 'sha',                          [hiragana.sha[2]]: 'shu',                         [hiragana.sha[4]]: 'sho',
  [hiragana.cha[0]]: 'cha',                          [hiragana.cha[2]]: 'chu',                         [hiragana.cha[4]]: 'cho',
  [hiragana.nya[0]]: 'nya',                          [hiragana.nya[2]]: 'nyu',                         [hiragana.nya[4]]: 'nyo',
  [hiragana.hya[0]]: 'hya',                          [hiragana.hya[2]]: 'hyu',                         [hiragana.hya[4]]: 'hyo',
  [hiragana.mya[0]]: 'mya',                          [hiragana.mya[2]]: 'myu',                         [hiragana.mya[4]]: 'myo',
  [hiragana.rya[0]]: 'rya',                          [hiragana.rya[2]]: 'ryu',                         [hiragana.rya[4]]: 'ryo',
  [hiragana.gya[0]]: 'gya',                          [hiragana.gya[2]]: 'gyu',                         [hiragana.gya[4]]: 'gyo',
  [hiragana.ja [0]]:  'ja',                          [hiragana.ja [2]]:  'ju',                         [hiragana.ja [4]]:  'jo',
  [hiragana.bya[0]]: 'bya',                          [hiragana.bya[2]]: 'byu',                         [hiragana.bya[4]]: 'byo',
  [hiragana.pya[0]]: 'pya',                          [hiragana.pya[2]]: 'pyu',                         [hiragana.pya[4]]: 'pyo',
  [hiragana.sokuon[0]]: '',
  [hiragana.smallYa[0]]: 'ya',                        [hiragana.smallYa[2]]: 'yu',                      [hiragana.smallYa[4]]: 'yo',
  [hiraganaChoon.u_]:   'uu', [hiraganaChoon.e_]:   'ee',
  [hiraganaChoon.fu_]: 'fuu', [hiraganaChoon.he_]: 'hee',
  [hiraganaSokuon.kka]: 'kka', [hiraganaSokuon.kki]: 'kki', [hiraganaSokuon.kku]: 'kku', [hiraganaSokuon.kke]: 'kke', [hiraganaSokuon.kko]: 'kko',
  [hiraganaSokuon.ssa]: 'ssa', [hiraganaSokuon.sshi]:'sshi', [hiraganaSokuon.ssu]: 'ssu', [hiraganaSokuon.sse]: 'sse', [hiraganaSokuon.sso]: 'sso',
  [hiraganaSokuon.tta]: 'tta', [hiraganaSokuon.cchi]:'cchi', [hiraganaSokuon.ttsu]:'ttsu', [hiraganaSokuon.tte]: 'tte', [hiraganaSokuon.tto]: 'tto',
  [hiraganaSokuon.ppa]: 'ppa', [hiraganaSokuon.ppi]: 'ppi', [hiraganaSokuon.ppu]: 'ppu', [hiraganaSokuon.ppe]: 'ppe', [hiraganaSokuon.ppo]: 'ppo',
  [hiraganaSokuon.kkya]:'kkya',                              [hiraganaSokuon.kkyu]:'kkyu',                            [hiraganaSokuon.kkyo]:'kkyo',
  [hiraganaSokuon.ssha]:'ssha',                              [hiraganaSokuon.sshu]:'sshu',                            [hiraganaSokuon.ssho]:'ssho',
  [hiraganaSokuon.ccha]:'ccha',                              [hiraganaSokuon.cchu]:'cchu',                            [hiraganaSokuon.ccho]:'ccho',
  [hiraganaSokuon.ppya]:'ppya',                              [hiraganaSokuon.ppyu]:'ppyu',                            [hiraganaSokuon.ppyo]:'ppyo',
} as const;

// prettier-ignore
export const toKatakana = {
    a: katakana.a  [0],   i: katakana.a [1],   u: katakana.a  [2],  e: katakana.a [3],   o: katakana.a  [4],
   ka: katakana.ka [0],  ki: katakana.ka[1],  ku: katakana.ka [2], ke: katakana.ka[3],  ko: katakana.ka [4],
   sa: katakana.sa [0], shi: katakana.sa[1],  su: katakana.sa [2], se: katakana.sa[3],  so: katakana.sa [4],
   ta: katakana.ta [0], chi: katakana.ta[1], tsu: katakana.ta [2], te: katakana.ta[3],  to: katakana.ta [4],
   na: katakana.na [0],  ni: katakana.na[1],  nu: katakana.na [2], ne: katakana.na[3],  no: katakana.na [4],
   ha: katakana.ha [0],  hi: katakana.ha[1],  fu: katakana.ha [2], he: katakana.ha[3],  ho: katakana.ha [4],
   ma: katakana.ma [0],  mi: katakana.ma[1],  mu: katakana.ma [2], me: katakana.ma[3],  mo: katakana.ma [4],
   ya: katakana.ya [0],                       yu: katakana.ya [2],                      yo: katakana.ya [4],
   ra: katakana.ra [0],  ri: katakana.ra[1],  ru: katakana.ra [2], re: katakana.ra[3],  ro: katakana.ra [4],
   wa: katakana.wa [0],                                                                 wo: katakana.wa [4],
    n: katakana.n  [0],
   ga: katakana.ga [0],  gi: katakana.ga[1],  gu: katakana.ga [2], ge: katakana.ga[3],  go: katakana.ga [4],
   za: katakana.za [0],  ji: katakana.za[1],  zu: katakana.za [2], ze: katakana.za[3],  zo: katakana.za [4],
   da: katakana.da [0],                                            de: katakana.da[3],  do: katakana.da [4],
   ba: katakana.ba [0],  bi: katakana.ba[1],  bu: katakana.ba [2], be: katakana.ba[3],  bo: katakana.ba [4],
   pa: katakana.pa [0],  pi: katakana.pa[1],  pu: katakana.pa [2], pe: katakana.pa[3],  po: katakana.pa [4],
  kya: katakana.kya[0],                      kyu: katakana.kya[2],                     kyo: katakana.kya[4],
  sha: katakana.sha[0],                      shu: katakana.sha[2],                     sho: katakana.sha[4],
  cha: katakana.cha[0],                      chu: katakana.cha[2],                     cho: katakana.cha[4],
  nya: katakana.nya[0],                      nyu: katakana.nya[2],                     nyo: katakana.nya[4],
  hya: katakana.hya[0],                      hyu: katakana.hya[2],                     hyo: katakana.hya[4],
  mya: katakana.mya[0],                      myu: katakana.mya[2],                     myo: katakana.mya[4],
  rya: katakana.rya[0],                      ryu: katakana.rya[2],                     ryo: katakana.rya[4],
  gya: katakana.gya[0],                      gyu: katakana.gya[2],                     gyo: katakana.gya[4],
   ja: katakana.ja [0],                       ju: katakana.ja [2],                      jo: katakana.ja [4],
  bya: katakana.bya[0],                      byu: katakana.bya[2],                     byo: katakana.bya[4],
  pya: katakana.pya[0],                      pyu: katakana.pya[2],                     pyo: katakana.pya[4],
   wi: katakana.wi [0],                       we: katakana.wi [3],                      woAlt: katakana.wi[4],
   va: katakana.va [0],  vi: katakana.va[1],  vu: katakana.va [2], ve: katakana.va[3],  vo: katakana.va [4],
  she: katakana.she[0],
   je: katakana.je [0],
  che: katakana.che[0],
  tsa: katakana.tsa[0], tsi: katakana.tsa[1],                     tse: katakana.tsa[3], tso: katakana.tsa[4],
   ti: katakana.ti [0],
   tu: katakana.tu [0],
   di: katakana.di [0],
   du: katakana.du [0],
   fa: katakana.fa [0],  fi: katakana.fa[1],                      fe: katakana.fa [3],  fo: katakana.fa [4],
  fya: katakana.fya[0],                      fyu: katakana.fya[2],                     fyo: katakana.fya[4],
 sokuon: katakana.sokuon[0],
  aSmall: katakana.smallA[0],
  ...katakanaChoon,
  ...katakanaSokuon
} as const;

// prettier-ignore
export const fromKatakana = {
  [katakana.a  [0]]:   'a', [katakana.a [1]]:   'i', [katakana.a  [2]]:   'u', [katakana.a [3]]: 'e',  [katakana.a  [4]]:   'o',
  [katakana.ka [0]]:  'ka', [katakana.ka[1]]:  'ki', [katakana.ka [2]]:  'ku', [katakana.ka[3]]: 'ke', [katakana.ka [4]]:  'ko',
  [katakana.sa [0]]:  'sa', [katakana.sa[1]]: 'shi', [katakana.sa [2]]:  'su', [katakana.sa[3]]: 'se', [katakana.sa [4]]:  'so',
  [katakana.ta [0]]:  'ta', [katakana.ta[1]]: 'chi', [katakana.ta [2]]: 'tsu', [katakana.ta[3]]: 'te', [katakana.ta [4]]:  'to',
  [katakana.na [0]]:  'na', [katakana.na[1]]:  'ni', [katakana.na [2]]:  'nu', [katakana.na[3]]: 'ne', [katakana.na [4]]:  'no',
  [katakana.ha [0]]:  'ha', [katakana.ha[1]]:  'hi', [katakana.ha [2]]:  'fu', [katakana.ha[3]]: 'he', [katakana.ha [4]]:  'ho',
  [katakana.ma [0]]:  'ma', [katakana.ma[1]]:  'mi', [katakana.ma [2]]:  'mu', [katakana.ma[3]]: 'me', [katakana.ma [4]]:  'mo',
  [katakana.ya [0]]:  'ya',                          [katakana.ya [2]]:  'yu',                         [katakana.ya [4]]:  'yo',
  [katakana.ra [0]]:  'ra', [katakana.ra[1]]:  'ri', [katakana.ra [2]]:  'ru', [katakana.ra[3]]: 're', [katakana.ra [4]]:  'ro',
  [katakana.wa [0]]:  'wa',                                                                            [katakana.wa [4]]:  'wo',
  [katakana.n  [0]]:   'n',
  [katakana.ga [0]]:  'ga', [katakana.ga[1]]:  'gi', [katakana.ga [2]]:  'gu', [katakana.ga[3]]: 'ge', [katakana.ga [4]]:  'go',
  [katakana.za [0]]:  'za', [katakana.za[1]]:  'ji', [katakana.za [2]]:  'zu', [katakana.za[3]]: 'ze', [katakana.za [4]]:  'zo',
  [katakana.da [0]]:  'da',                                                    [katakana.da[3]]: 'de', [katakana.da [4]]:  'do',
  [katakana.ba [0]]:  'ba', [katakana.ba[1]]:  'bi', [katakana.ba [2]]:  'bu', [katakana.ba[3]]: 'be', [katakana.ba [4]]:  'bo',
  [katakana.pa [0]]:  'pa', [katakana.pa[1]]:  'pi', [katakana.pa [2]]:  'pu', [katakana.pa[3]]: 'pe', [katakana.pa [4]]:  'po',
  [katakana.kya[0]]: 'kya',                          [katakana.kya[2]]: 'kyu',                         [katakana.kya[4]]: 'kyo',
  [katakana.sha[0]]: 'sha',                          [katakana.sha[2]]: 'shu',                         [katakana.sha[4]]: 'sho',
  [katakana.cha[0]]: 'cha',                          [katakana.cha[2]]: 'chu',                         [katakana.cha[4]]: 'cho',
  [katakana.nya[0]]: 'nya',                          [katakana.nya[2]]: 'nyu',                         [katakana.nya[4]]: 'nyo',
  [katakana.hya[0]]: 'hya',                          [katakana.hya[2]]: 'hyu',                         [katakana.hya[4]]: 'hyo',
  [katakana.mya[0]]: 'mya',                          [katakana.mya[2]]: 'myu',                         [katakana.mya[4]]: 'myo',
  [katakana.rya[0]]: 'rya',                          [katakana.rya[2]]: 'ryu',                         [katakana.rya[4]]: 'ryo',
  [katakana.gya[0]]: 'gya',                          [katakana.gya[2]]: 'gyu',                         [katakana.gya[4]]: 'gyo',
  [katakana.ja [0]]:  'ja',                          [katakana.ja [2]]:  'ju',                         [katakana.ja [4]]:  'jo',
  [katakana.bya[0]]: 'bya',                          [katakana.bya[2]]: 'byu',                         [katakana.bya[4]]: 'byo',
  [katakana.pya[0]]: 'pya',                          [katakana.pya[2]]: 'pyu',                         [katakana.pya[4]]: 'pyo',
  [katakana.wi [0]]:  'wi',                                                    [katakana.wi [3]]:  'we', [katakana.wi [4]]:  'wo',
  [katakana.va [0]]:  'va', [katakana.va[1]]:  'vi', [katakana.va [2]]:  'vu', [katakana.va[3]]: 've', [katakana.va [4]]:  'vo',
  [katakana.she[0]]: 'she',
  [katakana.je [0]]:  'je',
  [katakana.che[0]]: 'che',
  [katakana.tsa[0]]: 'tsa', [katakana.tsa[1]]: 'tsi',                           [katakana.tsa[3]]:'tse', [katakana.tsa[4]]:'tso',
  [katakana.ti [0]]:  'ti',
  [katakana.tu [0]]:  'tu',
  [katakana.di [0]]:  'di',
  [katakana.du [0]]:  'du',
  [katakana.fa [0]]:  'fa', [katakana.fa[1]]:  'fi',                            [katakana.fa [3]]: 'fe', [katakana.fa [4]]:  'fo',
  [katakana.fya[0]]: 'fya',                          [katakana.fya[2]]: 'fyu',                         [katakana.fya[4]]: 'fyo',
  [katakana.sokuon[0]]: '',
  [katakana.smallA[0]]:   'a',
  [katakanaChoon.a_]:   'aa', [katakanaChoon.i_]:   'ii', [katakanaChoon.u_]:   'uu', [katakanaChoon.e_]:  'ee', [katakanaChoon.o_]:   'oo',
  [katakanaChoon.ka_]: 'kaa', [katakanaChoon.ki_]: 'kii', [katakanaChoon.ku_]: 'kuu', [katakanaChoon.ke_]: 'kee', [katakanaChoon.ko_]: 'koo',
  [katakanaChoon.sa_]: 'saa', [katakanaChoon.shi_]:'shii', [katakanaChoon.su_]: 'suu', [katakanaChoon.se_]: 'see', [katakanaChoon.so_]: 'soo',
  [katakanaChoon.ta_]: 'taa', [katakanaChoon.chi_]:'chii', [katakanaChoon.tsu_]:'tsuu', [katakanaChoon.te_]: 'tee', [katakanaChoon.to_]: 'too',
  [katakanaChoon.na_]: 'naa', [katakanaChoon.ni_]: 'nii', [katakanaChoon.nu_]: 'nuu', [katakanaChoon.ne_]: 'nee', [katakanaChoon.no_]: 'noo',
  [katakanaChoon.ha_]: 'haa', [katakanaChoon.hi_]: 'hii', [katakanaChoon.fu_]: 'fuu', [katakanaChoon.he_]: 'hee', [katakanaChoon.ho_]: 'hoo',
  [katakanaChoon.ma_]: 'maa', [katakanaChoon.mi_]: 'mii', [katakanaChoon.mu_]: 'muu', [katakanaChoon.me_]: 'mee', [katakanaChoon.mo_]: 'moo',
  [katakanaChoon.ya_]: 'yaa',                                                    [katakanaChoon.yu_]: 'yuu',                           [katakanaChoon.yo_]: 'yoo',
  [katakanaChoon.ra_]: 'raa', [katakanaChoon.ri_]: 'rii', [katakanaChoon.ru_]: 'ruu', [katakanaChoon.re_]: 'ree', [katakanaChoon.ro_]: 'roo',
  [katakanaChoon.wa_]: 'waa',                                                                                                  [katakanaChoon.wo_]: 'woo',
  [katakanaChoon.n_]:   'nn',
  [katakanaChoon.ga_]: 'gaa', [katakanaChoon.gi_]: 'gii', [katakanaChoon.gu_]: 'guu', [katakanaChoon.ge_]: 'gee', [katakanaChoon.go_]: 'goo',
  [katakanaChoon.za_]: 'zaa', [katakanaChoon.ji_]: 'jii', [katakanaChoon.zu_]: 'zuu', [katakanaChoon.ze_]: 'zee', [katakanaChoon.zo_]: 'zoo',
  [katakanaChoon.da_]: 'daa',                                                            [katakanaChoon.de_]: 'dee', [katakanaChoon.do_]: 'doo',
  [katakanaChoon.ba_]: 'baa', [katakanaChoon.bi_]: 'bii', [katakanaChoon.bu_]: 'buu', [katakanaChoon.be_]: 'bee', [katakanaChoon.bo_]: 'boo',
  [katakanaChoon.pa_]: 'paa', [katakanaChoon.pi_]: 'pii', [katakanaChoon.pu_]: 'puu', [katakanaChoon.pe_]: 'pee', [katakanaChoon.po_]: 'poo',
  [katakanaChoon.kya_]:'kyaa',                              [katakanaChoon.kyu_]:'kyuu',                            [katakanaChoon.kyo_]:'kyoo',
  [katakanaChoon.sha_]:'shaa',                              [katakanaChoon.shu_]:'shuu',                            [katakanaChoon.sho_]:'shoo',
  [katakanaChoon.cha_]:'chaa',                              [katakanaChoon.chu_]:'chuu',                            [katakanaChoon.cho_]:'choo',
  [katakanaChoon.nya_]:'nyaa',                              [katakanaChoon.nyu_]:'nyuu',                            [katakanaChoon.nyo_]:'nyoo',
  [katakanaChoon.hya_]:'hyaa',                              [katakanaChoon.hyu_]:'hyuu',                            [katakanaChoon.hyo_]:'hyoo',
  [katakanaChoon.mya_]:'myaa',                              [katakanaChoon.myu_]:'myuu',                            [katakanaChoon.myo_]:'myoo',
  [katakanaChoon.rya_]:'ryaa',                              [katakanaChoon.ryu_]:'ryuu',                            [katakanaChoon.ryo_]:'ryoo',
  [katakanaChoon.gya_]:'gyaa',                              [katakanaChoon.gyu_]:'gyuu',                            [katakanaChoon.gyo_]:'gyoo',
  [katakanaChoon.ja_]:  'jaa',                              [katakanaChoon.ju_]:  'juu',                            [katakanaChoon.jo_]:  'joo',
  [katakanaChoon.bya_]:'byaa',                              [katakanaChoon.byu_]:'byuu',                            [katakanaChoon.byo_]:'byoo',
  [katakanaChoon.pya_]:'pyaa',                              [katakanaChoon.pyu_]:'pyuu',                            [katakanaChoon.pyo_]:'pyoo',
  [katakanaChoon.wi_]:  'wii',                                                        [katakanaChoon.we_]:  'wee', [katakanaChoon.woAlt_]: 'woo',
  [katakanaChoon.va_]:  'vaa', [katakanaChoon.vi_]:  'vii', [katakanaChoon.vu_]:  'vuu', [katakanaChoon.ve_]: 'vee', [katakanaChoon.vo_]:  'voo',
  [katakanaChoon.she_]:'shee',
  [katakanaChoon.je_]:  'jee',
  [katakanaChoon.che_]:'chee',
  [katakanaChoon.tsa_]:'tsaa', [katakanaChoon.tsi_]:'tsii',                              [katakanaChoon.tse_]:'tsee', [katakanaChoon.tso_]:'tsoo',
  [katakanaChoon.ti_]:  'tii',
  [katakanaChoon.tu_]:  'tuu',
  [katakanaChoon.di_]:  'dii',
  [katakanaChoon.du_]:  'duu',
  [katakanaChoon.fa_]:  'faa', [katakanaChoon.fi_]:  'fii',                              [katakanaChoon.fe_]: 'fee', [katakanaChoon.fo_]:  'foo',
  [katakanaChoon.fya_]:'fyaa',                              [katakanaChoon.fyu_]:'fyuu',                            [katakanaChoon.fyo_]:'fyoo',
  [katakanaSokuon.kka]: 'kka', [katakanaSokuon.kki]: 'kki', [katakanaSokuon.kku]: 'kku', [katakanaSokuon.kke]: 'kke', [katakanaSokuon.kko]: 'kko',
  [katakanaSokuon.ssa]: 'ssa', [katakanaSokuon.sshi]:'sshi', [katakanaSokuon.ssu]: 'ssu', [katakanaSokuon.sse]: 'sse', [katakanaSokuon.sso]: 'sso',
  [katakanaSokuon.tta]: 'tta', [katakanaSokuon.cchi]:'cchi', [katakanaSokuon.ttsu]:'ttsu', [katakanaSokuon.tte]: 'tte', [katakanaSokuon.tto]: 'tto',
  [katakanaSokuon.gga]: 'gga', [katakanaSokuon.ggi]: 'ggi', [katakanaSokuon.ggu]: 'ggu', [katakanaSokuon.gge]: 'gge', [katakanaSokuon.ggo]: 'ggo',
  [katakanaSokuon.dda]: 'dda',                                                            [katakanaSokuon.dde]: 'dde', [katakanaSokuon.ddo]: 'ddo',
  [katakanaSokuon.ppa]: 'ppa', [katakanaSokuon.ppi]: 'ppi', [katakanaSokuon.ppu]: 'ppu', [katakanaSokuon.ppe]: 'ppe', [katakanaSokuon.ppo]: 'ppo',
  [katakanaSokuon.ffu]: 'ffu',
  [katakanaSokuon.tti]: 'tti',
  [katakanaSokuon.kkaa]:'kkaa', [katakanaSokuon.kkii]:'kkii',
  [katakanaSokuon.ssaa]:'ssaa', [katakanaSokuon.ssee]:'ssee',
  [katakanaSokuon.ttaa]:'ttaa',
  [katakanaSokuon.kkya]:'kkya',                              [katakanaSokuon.kkyu]:'kkyu',                            [katakanaSokuon.kkyo]:'kkyo',
  [katakanaSokuon.ssha]:'ssha',                              [katakanaSokuon.sshu]:'sshu',                            [katakanaSokuon.ssho]:'ssho',
  [katakanaSokuon.ccha]:'ccha',                              [katakanaSokuon.cchu]:'cchu',                            [katakanaSokuon.ccho]:'ccho',
  [katakanaSokuon.ppya]:'ppya',                              [katakanaSokuon.ppyu]:'ppyu',                            [katakanaSokuon.ppyo]:'ppyo',
  [katakanaSokuon.ppaa]:'ppaa'
} as const;

export const punctuation = {
  punctuation: [
    "!",
    "%",
    "(",
    ",",
    "-",
    ".",
    "?",
    "―",
    "…",
    "、",
    "。",
    "！",
    "％",
    "（",
    "）",
    "／",
    "？",
    "・",
  ],
  symbol: ["↓", "▲", "△", "○", "㎝", "～", "ー"],
  space: [" ", "　"],
  digit: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "１"],
  latin: [
    "A",
    "C",
    "D",
    "E",
    "F",
    "I",
    "J",
    "L",
    "M",
    "N",
    "O",
    "P",
    "S",
    "T",
    "V",
    "W",
    "X",
    "a",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "m",
    "r",
    "u",
    "y",
  ],
  fullwidthLatin: ["Ｃ", "Ｐ", "ｃ", "ｍ"],
  other: ["〇"],
} as const;

export const punctuationChars = [
  ...punctuation.punctuation,
  ...punctuation.symbol,
  ...punctuation.space,
  ...punctuation.digit,
  ...punctuation.latin,
  ...punctuation.fullwidthLatin,
  ...punctuation.other,
] as const;

export const fromPunctuation = {
  "!": "!",
  "%": "%",
  "(": "(",
  ",": ",",
  "-": "-",
  ".": ".",
  "?": "?",
  "―": "-",
  "…": "...",
  "、": ",",
  "。": ".",
  "！": "!",
  "％": "%",
  "（": "(",
  "）": ")",
  "／": "/",
  "？": "?",
  "・": " ",

  "↓": "",
  "▲": "",
  "△": "",
  "○": "",
  "㎝": "cm",
  "～": "~",
  ー: "",

  " ": " ",
  "　": " ",

  "0": "0",
  "1": "1",
  "2": "2",
  "3": "3",
  "4": "4",
  "5": "5",
  "6": "6",
  "7": "7",
  "8": "8",
  "9": "9",
  "１": "1",

  A: "A",
  C: "C",
  D: "D",
  E: "E",
  F: "F",
  I: "I",
  J: "J",
  L: "L",
  M: "M",
  N: "N",
  O: "O",
  P: "P",
  S: "S",
  T: "T",
  V: "V",
  W: "W",
  X: "X",
  a: "a",
  c: "c",
  d: "d",
  e: "e",
  f: "f",
  g: "g",
  h: "h",
  i: "i",
  m: "m",
  r: "r",
  u: "u",
  y: "y",

  Ｃ: "C",
  Ｐ: "P",
  ｃ: "c",
  ｍ: "m",

  〇: "0",
} as const satisfies Record<(typeof punctuationChars)[number], string>;

const romajiMap: KanaToRomajiMap<KanaChar> = {
  ...fromHiragana,
  ...fromKatakana,
  ...fromPunctuation,
};

export const kanaChars: readonly KanaChar[] = [
  ...Object.values(toHiragana),
  ...Object.values(toKatakana),
  ...punctuationChars,
] as const;

export const KanaCharArkType = type.enumerated(...kanaChars);

export function romanize(text: string): string {
  let result = "";

  for (let i = 0; i < text.length; ) {
    if (text[i] === "っ" || text[i] === "ッ") {
      const next = romanize(text.slice(i + 1, i + 4))[0];
      result += next ?? "";
      i++;
      continue;
    }

    const trigram = text.slice(i, i + 3) as KanaChar;
    if (trigram in romajiMap) {
      result += romajiMap[trigram];
      i += 3;
      continue;
    }

    const bigram = text.slice(i, i + 2) as KanaChar;
    if (bigram in romajiMap) {
      result += romajiMap[bigram];
      i += 2;
    } else {
      const unigram = text[i] as KanaChar;
      result += romajiMap[unigram] ?? text[i];
      i++;
    }
  }

  return result;
}

export type Hiragana = typeof hiragana;
export type Katakana = typeof katakana;
export type Punctuation = typeof punctuation;
export type Kana<K> = K extends keyof Hiragana
  ? Record<K, HiraganaChar>
  : K extends keyof Katakana
    ? Record<K, KatakanaChar>
    : never;

export type HiraganaChar = (typeof toHiragana)[keyof typeof toHiragana];
export type KatakanaChar = (typeof toKatakana)[keyof typeof toKatakana];
export type PunctuationChar = (typeof punctuationChars)[number];
export type KanaChar = HiraganaChar | KatakanaChar | PunctuationChar;

export type FromHiragana = typeof fromHiragana;
export type FromKatakana = typeof fromKatakana;
export type KanaTable<C extends KanaChar> = Readonly<Record<string, readonly (C | null)[]>>;
export type KanaToRomajiMap<C extends KanaChar> = Readonly<Record<C, Romaji>>;
export type Romaji =
  | (typeof fromHiragana)[HiraganaChar]
  | (typeof fromKatakana)[KatakanaChar]
  | (typeof fromPunctuation)[PunctuationChar];
